name: Publish release

on:
  push:
    tags:
      - 'v*'

permissions: write-all 

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python "3.12"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build distribution
        run: |
          python -m build
      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}

    release:
      needs: publish
      runs-on: ubuntu-latest
      steps:
        - uses: marvinpinto/action-automatic-releases@latest
          name: Release
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false